# vi: ft=make
.PHONY: help install proto test docker deploy down reload info logs log

help: ## Show this help
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install: ## Install dependencies
	GOMODULES=off go get github.com/golang/protobuf/protoc-gen-go
	GOMODULES=off go get github.com/grpc-ecosystem/grpc-gateway
{{if not .Gateway}}
proto: ## Generate grpc service
	@protoc -I/usr/local/include \
		-I$(GOPATH)/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
		-I$(GOPATH)/src -I . \
		--lile-server_out=. --go_out=plugins=grpc,paths=source_relative:. \
		{{.Name}}.proto
{{else}}
proto: ## Generate grpc service with gateway
	@protoc -I/usr/local/include -I. \
		-I$(GOPATH)/src \
		-I$(GOPATH)/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
		--lile-server_out=. \
		--go_out=plugins=grpc,paths=source_relative:. \
		--grpc-gateway_out=logtostderr=true:. \
		{{.Name}}.proto
{{end}}
test: proto ## Run tests
	go test -p 1 -v ./...

docker: ## Build docker image
	@docker build . -t {{.Name}}:latest

deploy: ## Deploy pods to kubernetes
	@kubectl apply -f k8s.yml

down: ## Down pods
	@kubectl delete -f k8s.yml

reload: down deploy info ## Reload after app was rebuilt

refresh: down docker deploy info ## Rebuild image and restart service

info: ## Get cluster info
	@kubectl get all

logs: ## Show logs
	@kubectl logs -lapp={{.Name}} --container={{.Name}}

log: logs
